global:
  scrape_interval:     15s
  evaluation_interval: 30s

remote_write:
  - url: https://test-promscale.osc-fr1.scalingo.io/write
    # name: drop_expensive
#     write_relabel_configs:
#     - source_labels: [__name__]
#       regex:         expensive.*
#       action:        drop
#   - url: http://remote2/push
#     name: rw_tls
#     tls_config:
#       cert_file: valid_cert_file
#       key_file: valid_key_file
#     headers:
#       name: value
#
remote_read:
  - url: https://test-promscale.osc-fr1.scalingo.io/read
  # - url: http://remote1/read
#     read_recent: true
#     name: default
#   - url: http://remote3/read
#     read_recent: false
#     name: read_special
#     required_matchers:
#       job: special
#     tls_config:
#       cert_file: valid_cert_file
#       key_file: valid_key_file

scrape_configs:
- job_name: 0123service-xxx
  metrics_path: /metrics
  static_configs:
    - targets:
      - localhost:9090
